INSERT INTO public.issues (title, subtitle, description, date, pages) VALUES
('House of X #1:', 'The House That Xavier Built', 'Charles Xavier establishes Krakoa as a safe homeland for mutants.', '2019-07-24', 40),
('Powers of X #1:', 'The Last Dream of Professor X', 'Multiple timelines reveal Professor X''s plans and mutant futures.', '2019-07-31', 46),
('House of X #2:', 'The Uncanny Life of Moira X', 'Moira MacTaggert''s secret multiple lives shape mutant history.', '2019-08-07', 34),
('Powers of X #2:', 'We Are Together Now, You and I', 'Xavier and Magneto ally, and future mutants fight extinction.', '2019-08-14', 32),
('House of X #3:', 'Once More Into The Breach', 'X-Men attempt to destroy a dangerous Sentinel Mother Mold.', '2019-08-28', 33),
('Powers of X #3:', 'This Is What You Do', 'Future mutant rebels attack Nimrod, sacrificing everything.', '2019-08-21', 32),
('House of X #4:', 'It Will Be Done', 'X-Men suffer tragic losses fighting Mother Mold in space.', '2019-09-04', 33),
('Powers of X #4', 'Something Sinister', 'Xavier and Magneto form an uneasy alliance with Mister Sinister.', '2019-09-11', 31),
('House of X #5:', 'Society', 'Mutants create a new society.', '2019-09-18', 34),
('Powers of X #5:', 'For The Children', 'Mutant leaders prepare for evolution as cosmic beings observe.', '2019-09-25', 33),
('House of X #6:', 'I Am Not Ashamed', 'Xavier publicly declares Krakoa''s independence, uniting mutants.', '2019-10-02', 32),
('Powers of X #6:', 'House of X', 'Moira''s hidden plans align, securing a new mutant era.', '2019-10-09', 50),
('X-Men #1:', 'Pax Krakoa', 'Cyclops rescues mutants and shows his family''s new lunar home.', '2019-10-16', 40),
('Marauders #1:', 'I''m On A Boat', 'Kate Pryde forms a mutant team at sea, rescuing stranded mutants.', '2019-10-23', 40),
('Excalibur #1:', 'Verse I: The Accolade of Betsy Braddock', 'Betsy Braddock becomes Captain Britain, facing Morgan Le Fay''s magic.', '2019-10-30', 40),
('New Mutants #1:', 'The Sextant', 'New Mutants adventure into space searching for Cannonball.', '2019-11-06', 40),
('X-Force #1:', 'Hunting Ground', 'A Quiet Council member is killed!', '2019-11-06', 40),
('Fallen Angels #1:', 'Bushido', 'Psylocke leads X-23 and Cable to stop a digital drug, Overclock.', '2019-11-13', 40),
('X-Men #2:', 'Summoner', 'X-Men encounter a mysterious mutant tied to Apocalypse''s past.', '2019-11-13', 32),
('X-Men #3:', 'Hordeculture', 'Elderly botanists challenge X-Men, stealing Krakoan plants.', '2019-12-04', 32),
('Excalibur #2:', 'Verse II: A Tower of Flowers', 'Excalibur try to save Rogue.', '2019-11-20', 32),
('Excalibur #3:', 'Verse III: Three Covenants', 'Excalibur battles Morgan Le Fay, as Apocalypse plots magic alliances.', '2019-12-04', 32),
('Excalibur #4:', 'Verse IV: Fall Back and Think of England!', 'Excalibur retreats to rethink how to save London from magic siege.', '2019-12-18', 32),
('Excalibur #5:', 'Verse V: Panic on the Streets of London', 'Excalibur contains chaos from Morgan Le Fay''s dark magic.', '2020-01-01', 32),
('Marauders #2:', 'The Red Coronation', 'Emma Frost appoints a leader of Hellfire Trading Company.', '2019-11-27', 32),
('New Mutants #2:', 'Space Jail', 'New Mutants are imprisoned after trouble in Shi''ar space.', '2019-11-27', 28),
('X-Force #2:', 'The Sword of Damocles', 'X-Force hunts down assassins.', '2019-11-27', 32),
('X-Force #3:', 'The Skeleton Key', 'X-Force uncovers Domino''s stolen powers, fighting assassins.', '2019-12-18', 32),
('Fallen Angels #2:', 'Shoto', 'Psylocke trains her team, tracking villain Apoth''s Overclock drug.', '2019-11-27', 28),
('Fallen Angels #3:', 'Seppuku', 'Psylocke confronts her past while Apoth manipulates X-23.', '2019-12-11', 28),
('Fallen Angels #4:', 'Shikatsu', 'Psylocke faces a tough decision on stopping Apoth''s threat.', '2020-01-01', 28),
('Fallen Angels #5:', 'Sensei', 'Psylocke prepares her team for a final fight against Apoth.', '2020-01-15', 28),
('Fallen Angels #6:', 'Conclusion', 'Psylocke''s team aim to end Overclock''s threat.', '2020-02-26', 28),
('Marauders #3:', 'The Bishop in Black', 'Bishop joins Marauders, investigating threats to mutants.', '2019-12-04', 28),
('New Mutants #3:', 'To The Grave', 'Armor tries helping mutants, stumbling into a hostage crisis.', '2019-12-11', 28),
('New Mutants #4:', 'Fast and Furious', 'Armor''s group fights criminals exploiting mutant medicines.', '2019-12-26', 28),
('New Mutants #5:', 'Endangered Birds', 'New Mutants caught in Shi''ar politics complicating their return.', '2020-01-08', 28),
('New Mutants #6:', 'Not As Hoped', 'New Mutants struggle to return home after space misadventure.', '2020-01-22', 28),
('New Mutants #7:', 'Spoilers', 'Young mutants return home, reflecting on tough lessons learned.', '2020-02-12', 28),
('Marauders #4:', 'The Red Bishop', 'Bishop deals with a sea-based hostage situation.', '2019-12-18', 28),
('X-Force #4:', 'Blood Economics', 'Beast investigates funding behind attacks on Krakoa.', '2020-01-08', 32),
('X-Force #5:', 'Necessary Force', 'X-Force looks to ensure Krakoa''s safety.', '2020-01-29', 32),
('X-Men #4:', 'Global Economics', 'Xavier negotiates peace as Cyclops stops an assassination attempt.', '2020-01-01', 28),
('X-Men #5:', 'Into The Vault', 'X-Men explore a vault filled with advanced beings.', '2020-01-29', 28),
('X-Men/Fantastic Four #1:', 'The Impossible Boy', 'Franklin Richards struggles with his powers, sparking tension between teams.', '2020-02-05', 40),
('X-Men/Fantastic Four #2:', 'Broken Borders', 'Franklin seeks Doctor Doom''s help, causing team conflicts.', '2020-03-18', 32),
('X-Men/Fantastic Four #3:', 'To The Victor', 'Teams unite against Doom to rescue Franklin and Valeria.', '2020-07-15', 32),
('X-Men/Fantastic Four #4:', 'Welcome To The New World', 'Peace is reached, or is it?.', '2020-08-05', 32),
('Marauders #5:', 'A Time To Sow', 'Sebastian Shaw secretly plots against Kate Pryde.', '2020-01-01', 28),
('Marauders #6:', 'A Time To Reap', 'Shaw''s betrayal.', '2020-01-22', 28),
('Excalibur #6:', 'Verse VI: Watch The Throne', 'Excalibur defeats Morgan Le Fay, ending the magical war.', '2020-01-22', 28),
('X-Force #6:', 'Intelligence', 'X-Force discovers dangerous bio-weapons and repurposes them.', '2020-02-12', 32),
('X-Men #6:', 'The Oracle', 'Mystique plots secretly while completing a mission for Krakoa.', '2020-05-12', 28),
('X-Men #7:', 'Lifedeath', 'Mutants debate resurrection through Apocalypse''s Crucible ritual.', '2020-02-26', 36),
('Excalibur #7:', 'Verse VII', 'Excalibur hunts dangerous Warwolves.', '2020-02-12', 28),
('Excalibur #8:', 'Verse VIII', 'Excalibur successfully captures the Warwolves.', '2020-02-26', 28),
('Marauders #7:', 'From Emma, With Love', 'Emma mourns a friend and plots revenge.', '2020-02-05', 28),
('Marauders #8:', 'Furious Anger', 'Storm and Emma retaliate against Kate''s attackers.', '2020-02-19', 28),
('X-Force #7:', 'Domino Has Fallen', 'Domino returns shaken after her powers are exploited.', '2020-02-26', 32),
('X-Force #8:', 'Game of Dominoes', 'Domino fights to regain control.', '2020-03-11', 32),
('Giant Size X-Men: Jean Grey and Emma Frost #1:', 'Into The Storm', 'Jean and Emma enter Storm''s mind to save her from infection.', '2020-02-26', 36),
('New Mutants #8:', 'A-Hunting We Will Go', 'Boom-Boom leads mutants into Krakoa''s jungle to battle threats.', '2020-03-04', 28),
('Marauders #9:', 'Journey To The Centre of Pyro', 'Pyro confronts personal demons during a risky mission.', '2020-03-04', 28),
('Cable #1:', 'Big Guns', 'Cable finds an alien sword.', '2020-03-11', 40),
('X-Men #8:', 'Swarm', 'X-Men defend against an invading alien Brood swarm.', '2020-03-11', 28),
('X-Men #9:', 'The King Egg', 'X-Men attempt to stop the Brood invasion.', '2020-03-25', 28),
('X-Force #9:', 'The Moral Jungle', 'X-Force intervenes as plant experiments spiral out of control.', '2020-06-20', 32),
('X-Force #10:', 'The Deadly Garden', 'X-Force battles dangerous plant creatures in a chaotic lab.', '2020-07-08', 32),
('Excalibur #9:', 'Verse IX: Schools of Magic', 'Apocalypse trains Rictor in mutant magic.', '2020-03-25', 28),
('Giant Size X-Men: Nightcrawler #1:', 'Haunted Mansion', 'Nightcrawler investigates strange events at Xavier School.', '2020-03-25', 40),
('Marauders #10:', 'Leave None To Tell The Tale', 'Marauders eliminate human traffickers threatening mutants.', '2020-07-15', 40),
('Hellions #1:', 'Let Them Be Snakes', 'Sinister forms Hellions, an unstable mutant strike team.', '2020-03-25', 40),
('Hellions #2:', 'Blood Work', 'Hellions battle Madelyne Pryor and her clone army.', '2020-07-29', 28),
('Hellions #3:', 'Nothing People', 'Hellions cope with trauma after fighting Madelyne.', '2020-09-02', 28),
('Hellions #4:', 'Love Bleeds', 'Hellions recover as Sinister plans new missions.', '2020-09-23', 28),
('New Mutants #9:', 'Something Rotten In…', 'Armor''s team uncovers a mutant conspiracy abroad.', '2020-03-18', 28),
('New Mutants #10:', 'Parasomnia', 'New Mutants rescue a mutant trapped in nightmare illusions.', '2020-09-02', 28),
('New Mutants #11:', 'Ice Cream Dreams', 'New Mutants help a rescued mutant recover through kindness.', '2020-09-16', 28),
('Marauders #11:', 'To Live and Die on Krakoa', 'Marauders investigate why Kate Pryde can''t resurrect.', '2020-08-19', 28),
('Marauders #12:', 'The New Phase', 'The Marauders are revitalized.', '2020-09-02', 28),
('Excalibur #10:', 'Verse X: A Crooked World', 'Excalibur fixes a twisted alternate reality.', '2020-07-15', 28),
('Wolverine #1:', 'The Flower Cartel', 'Wolverine hunts a cartel stealing Krakoan drugs.', '2020-02-19', 32),
('Wolverine #2:', 'Your Own Worst Enemy', 'Wolverine fights mind control by the Pale Girl.', '2020-03-25', 32),
('Wolverine #3:', 'You Didn''t See Nothing', 'Wolverine ends the Pale Girl''s drug operation.', '2020-07-22', 32),
('X-Factor #1:', 'Suite No. 1: Prelude: Aurora Moratorium', 'Northstar forms X-Factor to investigate his sister''s death.', '2020-07-29', 40),
('Wolverine #1:', 'Catacombs', 'Wolverine discovers Dracula''s vampire plot in Paris.', '2020-02-19', 32),
('Wolverine #4:', 'The Red Tavern', 'Wolverine and Omega Red uncover Dracula''s vampire hideout.', '2020-09-09', 32),
('Wolverine #5:', 'Bloodclocks', 'Wolverine fights vampires to stop Dracula''s deadly plans.', '2020-10-07', 32),
('Giant Size X-Men: Magneto #1:', NULL, 'Magneto creates a new mutant island with Namor''s help.', '2020-07-15', 40),
('Cable #2:', 'The Five In One', 'Cable investigates mutant baby kidnappings.', '2020-07-18', 28),
('Cable #3:', 'Ace In The Pouch', 'Cable and Deadpool battle aliens after an ancient sword.', '2020-08-19', 28),
('Cable #4:', 'The Five In One', 'Cable protects Earth with Stepford Cuckoos.', '2020-09-30', 28),
('Incoming #1', NULL,'Heroes investigate a murder hinting at a cosmic threat.', '2019-12-26', 92),
('Empyre: Avengers #0', NULL, 'Avengers uncover a brewing alien war.', '2020-07-08', 40),
('Empyre: Fantastic Four #0', NULL, 'Fantastic Four encounter young Kree and Skrull before war.', '2020-07-08', 40),
('Empyre #1', NULL, 'Kree/Skrull alliance arrives, revealing Cotati''s betrayal.', '2020-07-15', 40),
('Empyre #2', NULL, 'Heroes battle global alien invasion by Cotati.', '2020-07-29', 28),
('X-Men #10:', 'Fire', 'Vulcan defends the moon base against alien plants.', '2020-07-29', 28),
('Empyre X-Men #1:', 'Empyre', 'Mutant zombies rise during Cotati invasion on Genosha.', '2020-07-22', 28),
('Empyre X-Men #2:', 'Growing Strong', 'X-Men team up with Hordeculture against the Cotati.', '2020-07-29', 28),
('Empyre #3', NULL, 'Earth''s heroes unite as Cotati''s full threat emerges.', '2020-08-05', 28),
('Empyre X-Men #3:', 'Staff Infection', 'Magik controls mutant zombies against Cotati invaders.', '2020-08-05', 28),
('Empyre X-Men #4:', 'Un-Ring', 'X-Men and allies rally against Cotati invasion on Genosha.', '2020-08-12', 28),
('Empyre #4', NULL, 'Cotati target Wakanda; Avengers defend fiercely.', '2020-08-19', 28),
('Empyre #5', NULL, 'Heroes uncover betrayal within Hulkling''s ranks.', '2020-09-02', 28),
('X-Men #11:', 'One War, One Mutant', 'Magneto takes on the invading Cotati.', '2020-08-26', 28),
('Empyre #6', NULL, 'Heroes end Cotati invasion; peace returns to the galaxy.', '2020-09-16', 40),
('Empyre: Aftermath Avengers #1', NULL, 'Avengers handle political aftermath.', '2020-09-23', 36),
('Empyre: Fallout Fantastic Four #1', NULL, 'Fantastic Four secure peace.', '2020-09-23', 36),
('X-Factor #2:', 'Mojoverse Sonata XF.3 OP. 45, Danse Macabre', 'X-Factor investigates deadly Mojoverse streaming entertainment.', '2020-09-02', 28),
('X-Factor #3:', ' Mojoverse Sonata The 2nd, A Celestial Rondo', 'X-Factor battles in Mojoverse to save friends.', '2020-09-20', 28),
('New Mutants #12:', 'Monster Machine', 'New Mutants fight mutant-hunting machines.', '2020-10-07', 28),
('Giant Size X-Men: Fantomex #1:', 'The World', 'Fantomex revisits The World to rescue a lost being.', '2020-08-05', 36),
('Giant Size X-Men: Storm #1:', 'Disintegration', 'Storm fights infection within The World to save herself.', '2020-09-16', 36),
('X-Force #11:', 'Red Dawn', 'Mikhail Rasputin kidnaps Kid Omega.', '2020-09-24 ', 32),
('X-Force #12:', 'The Cerebro Sword', 'Enemies obtain Cerebro, threatening mutantkind.', '2020-09-23', 32),
('Excalibur #11:', 'Verse XI', 'Excalibur prepares for Apocalypse''s ritual sacrifice.', '2020-08-26', 28),
('Excalibur #12:', 'Verse XII', 'Apocalypse opens gateway to lost land Arakko, starting new conflict.', '2020-09-16', 28),
('X-Men #12:', 'Amenth', 'Summoner reveals Arakko''s past and warns of coming war.', '2020-09-16', 28),
('X of Swords: Creation', 'X of Swords: Part 1', 'Krakoa gathers swordbearers to face Apocalypse''s ancient children.', '2020-09-23', 68),
('X-Factor #4:', 'X of Swords: Part 2', 'X-Men face consequences of death in Otherworld tournament.', '2020-10-07', 28),
('Wolverine #6:', 'X of Swords: Part 3', 'Wolverine seeks the Muramasa blade for the tournament.', '2020-10-07', 32),
('X-Force #13:', 'X of Swords: Part 4', 'Wolverine teams with Solem to retrieve twin Muramasa blades.', '2020-10-07', 32),
('Marauders #13:', 'X of Swords: Part 5', 'Storm goes to Wakanda for the Skybreaker sword, confronting her past.', '2020-10-07', 28),
('Hellions #5:', 'X of Swords: Part 6', 'Hellions attempt sabotage in Otherworld but fail disastrously.', '2020-10-07', 28),
('New Mutants #13:', 'X of Swords: Part 7', 'Magik trains Cypher, who doubts his combat readiness.', '2020-10-21', 28),
('Cable #5:', 'X of Swords: Part 8', 'Cable, Cyclops, and Jean encounter an alien threat on a space station.', '2020-10-14', 28),
('Excalibur #13:', 'X of Swords: Part 9', 'Brian yields the Sword of Might, Betsy claims the Starlight Sword.', '2020-10-07', 28),
('X-Men #13:', 'X of Swords: Part 10', 'Apocalypse recovers, retrieving the Scarab sword to face Genesis.', '2020-10-21', 28),
('X of Swords: Stasis', 'X of Swords: Part 11', 'Krakoan and Arakkii champions meet and prepare in Otherworld.', '2020-10-28', 40),
('X-Men #14:', 'X of Swords: Part 12', 'Genesis reveals her past and the true enemy behind the tournament.', '2020-11-04', 28),
('Marauders #14:', 'X of Swords: Part 13', 'Champions engage in strange contests.', '2020-10-21', 28),
('Marauders #15:', 'X of Swords: Part 14', 'Duels begin, catching Krakoans off guard.', '2020-10-21', 28),
('Excalibur #14:', 'X of Swords: Part 15', 'Betsy Braddock comes up against against Isca.', '2020-10-20', 28),
('Wolverine #7:', 'X of Swords: Part 16', 'Wolverine fights through brutal and bizarre challenges.', '2020-10-21', 32),
('X-Force #14:', 'X of Swords: Part 17', 'Storm combats Death in a vampire realm.', '2020-20-11', 32),
('Hellions #6:', 'X of Swords: Part 18', 'Hellions fail in a disastrous ambush during sabotage attempt.', '2020-11-18', 28),
('Cable #6:', 'X of Swords: Part 19', 'Cyclops and Jean''s intervene.', '2020-11-18', 28),
('X-Men #15:', 'X of Swords: Part 20', 'Cyclops and Jean rally mutants; Apocalypse prepares final duel.', '2020-11-25', 28),
('Excalibur #15:', 'X of Swords: Part 21', 'Full battle breaks out against Arakko.', '2020-11-11', 28),
('X of Swords: Destruction:', 'X of Swords: Part 22', 'Apocalypse reunites with family.', '2020-11-25', 56);